Error in push finish
MerginMaps/server pull request #321
Opened 2024-11-07 15:13 UTC by harminius

Task: https://github.com/MerginMaps/server-private/issues/2558

Situation:
When creating a blank project, the `latest_project_files` record is also created and the `file_history_ids` column is set to `{}`.
This field is used in the files map when creating a project version.
Unfortunately, this field is nullable and for old projects it's `null`. 
This makes project version creation fail when uploading through webapp drag&drop.

Solution
When the `file_history_ids` column is `null` return an empty dict.

2024-11-11 12:20 UTC, varmar05 requested changes

2024-11-11 12:20 UTC, varmar05 commented on server/mergin/sync/models.py
> +                    self.project.latest_project_files.file_history_ids or {}
Could you add a test?

2024-11-11 12:21 UTC, varmar05 commented on server/mergin/sync/commands.py
> +        user = User.query.get(int(user))
I would probably go with username

2024-11-11 12:23 UTC, varmar05 commented
"Make file_history_ids not nullable?" It was meant to be nullable and updated only on demand (first pull / get info) as whole migration would have been very heavy. So probably we maybe want to cache files ids if it is null as a fix.

2024-11-20 14:51 UTC, harminius commented on server/mergin/sync/commands.py
> +        user = User.query.get(int(user))
Done

2024-11-20 14:51 UTC, harminius commented on server/mergin/sync/models.py
> +                    self.project.latest_project_files.file_history_ids or {}
Done

2024-11-20 14:54 UTC, harminius commented
> "Make file_history_ids not nullable?" It was meant to be nullable and updated only on demand (first pull / get info) as whole migration would have been very heavy. So probably we maybe want to cache files ids if it is null as a fix.

Actually, I found out the latest project files are cached in this scenario.

That's why the problem is only in empty projects. The caching method finds no files to cache and keeps the column `null`.

2024-11-20 15:18 UTC, varmar05 commented
> Actually, I found out the latest project files are cached in this scenario.
> 
> That's why the problem is only in empty projects. The caching method finds no files to cache and keeps the column `null`.

If caching method finds no files then I guess it should set it to empty array rather that NULL which should be only used if that row has never been cached.

2024-11-21 08:35 UTC, merged