Introduce push_finished signal
MerginMaps/server pull request #331
Opened 2024-11-14 14:33 UTC by MarcelGeo

Itroducing new push finished signal to handle successful pushes to projects.

2024-11-15 07:19 UTC, MarcelGeo commented on server/mergin/tests/utils.py
> +    assert resp_push_finish.status_code == 200
I am returning tuple from push to proper handling of responses for push start and finish. In some tests I need chcem also response from push. I don't want to push manually.

2024-11-15 08:18 UTC, MarcelGeo commented on server/mergin/tests/utils.py
> +    assert resp_push_finish.status_code == 200
This method is used for cases, where you do not need to handle response object.

2024-11-18 13:40 UTC, varmar05 requested changes

2024-11-18 13:40 UTC, varmar05 commented on server/mergin/tests/utils.py
> +def push_file_start(project, filename, client, mocked_changes_data=None) -> Tuple:
add docstring

2024-11-18 13:40 UTC, varmar05 commented on server/mergin/tests/utils.py
> +    print(resp.json)
rm

2024-11-18 13:40 UTC, varmar05 commented on server/mergin/tests/utils.py
> +    assert push_finish.status_code == 200
let's also return resp instead, it might comes in handy

2024-11-18 14:33 UTC, varmar05 approved these changes

2024-11-18 16:02 UTC, merged